// Deterministic skill/certification vocabulary used by the baseline scorer and the guardrails.
// Each entry: canonical name -> regex aliases. Extend freely; matching is case-insensitive.

export const CERTIFICATIONS: Record<string, RegExp> = {
  "ISO/IEC 27001 Lead Auditor": /\biso\s*(\/\s*iec\s*)?27001\s*(lead\s*auditor|la)\b/i,
  "ISO/IEC 27001 Lead Implementer": /\biso\s*(\/\s*iec\s*)?27001\s*(lead\s*implementer|li)\b/i,
  "ISO 22301 Lead Auditor": /\biso\s*22301\b/i,
  "ISO 42001": /\biso\s*(\/\s*iec\s*)?42001\b/i,
  CISSP: /\bcissp\b/i,
  CISA: /\bcisa\b/i,
  CISM: /\bcism\b/i,
  CRISC: /\bcrisc\b/i,
  CGEIT: /\bcgeit\b/i,
  CCSP: /\bccsp\b/i,
  CCSK: /\bccsk\b/i,
  CEH: /\bceh\b|certified ethical hacker/i,
  OSCP: /\boscp\b/i,
  "CompTIA Security+": /\bsecurity\+|comptia security\b/i,
  "CompTIA CySA+": /\bcysa\+/i,
  CIPP: /\bcipp(\/[a-z]+)?\b/i,
  CIPM: /\bcipm\b/i,
  CIPT: /\bcipt\b/i,
  "PCI QSA": /\bpci\s*qsa\b|\bqsa\b/i,
  GIAC: /\bgiac\b|\bgsec\b|\bgcih\b/i,
  "AWS Security Specialty": /\baws (certified )?security[- ]specialty\b/i,
  "Azure Security Engineer (AZ-500)": /\baz-?500\b/i,
  "Microsoft SC-900": /\bsc-?900\b/i,
  "COBIT 2019": /\bcobit\b/i,
  ITIL: /\bitil\b/i,
  PMP: /\bpmp\b/i,
  "Certified Internal Auditor (CIA)": /\bcertified internal auditor\b/i,
  DPO: /\bcertified (data protection officer|dpo)\b/i,
};

export const SKILLS: Record<string, RegExp> = {
  "ISO 27001": /\biso\s*(\/\s*iec\s*)?27001\b/i,
  "ISO 27002": /\biso\s*(\/\s*iec\s*)?27002\b/i,
  "ISO 27701": /\biso\s*(\/\s*iec\s*)?27701\b/i,
  "SOC 2": /\bsoc\s*2\b|\bsoc2\b/i,
  "SOC 1": /\bsoc\s*1\b/i,
  "PCI DSS": /\bpci[- ]?dss\b/i,
  HIPAA: /\bhipaa\b/i,
  GDPR: /\bgdpr\b/i,
  "DPDP Act": /\bdpdp\b|digital personal data protection/i,
  "NIST CSF": /\bnist\s*(csf|cybersecurity framework)\b/i,
  "NIST 800-53": /\b800-53\b/i,
  "CIS Controls": /\bcis (controls|benchmarks?)\b/i,
  "RBI guidelines": /\brbi\b/i,
  SEBI: /\bsebi\b/i,
  GRC: /\bgrc\b|governance,? risk,? (and|&) compliance/i,
  "Risk assessment": /\brisk assessments?\b/i,
  "Risk management": /\brisk management\b/i,
  "Third-party risk management": /\b(third[- ]party|vendor|supplier) risk\b|\btprm\b/i,
  "Internal audit": /\binternal audits?\b/i,
  "IT audit": /\bit audits?\b|\bit general controls\b|\bitgc\b/i,
  "Compliance management": /\bcompliance (management|monitoring|program)\b/i,
  "Policy development": /\b(security )?polic(y|ies) (development|writing|drafting|management)\b|\bpolicies and procedures\b/i,
  "Business continuity": /\bbusiness continuity\b|\bbcp\b|\bbcms\b/i,
  "Disaster recovery": /\bdisaster recovery\b|\bdr\s*plan/i,
  "Incident response": /\bincident (response|management|handling)\b/i,
  "Vulnerability management": /\bvulnerability (management|assessment)\b|\bvapt\b/i,
  "Penetration testing": /\bpen(etration)? test(ing)?\b/i,
  SIEM: /\bsiem\b|\bsplunk\b|\bqradar\b|\bsentinel\b/i,
  SOC: /\bsecurity operations cent(er|re)\b|\bsoc analyst\b/i,
  "Cloud security": /\bcloud security\b/i,
  AWS: /\baws\b|amazon web services/i,
  Azure: /\bazure\b/i,
  GCP: /\bgcp\b|google cloud/i,
  "Identity and access management": /\b(iam|identity and access management|access reviews?)\b/i,
  "Data privacy": /\b(data )?privacy\b/i,
  "Data loss prevention": /\bdlp\b|data loss prevention/i,
  "Security awareness": /\bsecurity awareness\b/i,
  "Asset management": /\basset (inventory|management)\b/i,
  "Change management": /\bchange management\b/i,
  "Control testing": /\bcontrol(s)? testing\b|\btest(ing)? of controls\b/i,
  "Gap assessment": /\bgap (assessment|analysis)\b/i,
  "Audit management": /\baudit (planning|management|lifecycle|fieldwork)\b/i,
  "Risk register": /\brisk register\b/i,
  "Security architecture": /\bsecurity architecture\b/i,
  Firewalls: /\bfirewalls?\b/i,
  "Network security": /\bnetwork security\b/i,
  "Endpoint security": /\bendpoint (security|protection)\b|\bedr\b/i,
  DevSecOps: /\bdevsecops\b/i,
  Python: /\bpython\b/i,
  "Power BI": /\bpower ?bi\b/i,
  Excel: /\b(ms |advanced )?excel\b/i,
  ServiceNow: /\bservicenow\b/i,
  Archer: /\b(rsa )?archer\b/i,
  OneTrust: /\bonetrust\b/i,
  "MetricStream": /\bmetricstream\b/i,
  Vanta: /\bvanta\b/i,
  Drata: /\bdrata\b/i,
  "Stakeholder management": /\bstakeholder management\b/i,
  "Report writing": /\breport writing\b|\baudit reports?\b/i,
};

export function termsIn(text: string, vocab: Record<string, RegExp>): string[] {
  const out: string[] = [];
  for (const [name, re] of Object.entries(vocab)) if (re.test(text)) out.push(name);
  return out;
}
